import Head from 'next/head';
import Center from "../components/Center/Center";
import Sidebar from "../components/Sidebar/Sidebar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Skilly Tree</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main_container}>
        <Center />
        <Sidebar />
      </main>

    </div>
  )
}
